### ISSUE TITLE
Replace property tree object with boost property tree

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/tools#109]
Boost already supports a property tree object that can handle xml reading,there is no need to have our own.

**Comment by JoshuaSBrown** [comment]
https://www.boost.org/doc/libs/1_69_0/doc/html/property_tree.html

**Comment by JensWehner** [comment]
Do you want to wrap it in the property class or do you want to change it everywhere?. Can we just cleverly wrap it there and be done?

**Comment by JoshuaSBrown** [comment]
I don't really care, this is not a priority. I just know that the boost library will probably be better supported moving forward.

**Comment by JensWehner** [comment]
we could also switch from xml to json in a heartbeat

**Comment by JensWehner** [comment]
After all the reworking with property class, I do not think this rework is sensible or usefule anymore
