### ISSUE TITLE
Replace random2 with std::random implementation

### ISSUE THREAD

**Issue by JensWehner** [votca/tools#118]

**Comment by junghans** [comment]
Ping @JensWehner

**Comment by JensWehner** [comment]
Yeah last time I tried I got compilation problems with icc. So this is postponed.

**Comment by JensWehner** [comment]
The error I get `./votca_property: symbol lookup error: ./votca_property: undefined symbol: __libm_rcp_table_256
`

**Comment by junghans** [comment]
Hmm, this means icc links in the wrong libm, you might miss an LD_LIBRARY_PATH in your intel module.

**Comment by JensWehner** [comment]
but which one?

**Comment by JensWehner** [comment]
I am working on it.
