### ISSUE TITLE
MKL always links sequentially instead of the parallel versions

### ISSUE THREAD

**Issue by JensWehner** [votca/tools#159]
It has to do with https://github.com/votca/tools/commit/719d51188b01538cd3f7de061c693640999081f9

I do not really know what is happening, because we set the threading layer here

https://github.com/votca/tools/blob/master/CMakeLists.txt

**Comment by JensWehner** [comment]
@junghans I still do not fully understand why we have the FindMKL in csg and tools. Can you explain it once more?

**Comment by JensWehner** [comment]
we have `find_mkl_library(NAME ThreadLayer LIBRARY_NAME mkl_sequential)` in all the CMakeLists

**Comment by junghans** [comment]
Can you change the default of `MKL_THREAD_LAYER` back?

**Comment by JensWehner** [comment]
Yeah sure, but the default should not be used, because I set it explicitly before that. That confuses me.

**Comment by JensWehner** [comment]
https://github.com/votca/tools/pull/160
