### ISSUE TITLE
Replace fftw interface with Eigen fftw 

### ISSUE THREAD

**Issue by JensWehner** [votca/tools#181]
would allow us to use eigen internal implementation without fftw library 
and otherwise we could use fftw or MKL as a backend. 

https://eigen.tuxfamily.org/dox/unsupported/group__FFT__Module.html

https://gitlab.math.ethz.ch/NumCSE/NumCSE/blob/43c3152296a97f4a927cd82fe3c19ac0c64537e4/CMake/Macros/set_eigen_fft_backend.cmake

**Comment by junghans** [comment]
Sounds good to me, that would give us an option to keep functionality even if fftw isn't there.

**Comment by JensWehner** [comment]
Yeah unfortunately, the eigen interface does not yet support mkl, but it would still be a nice extension

**Comment by junghans** [comment]
Huh? Doesn't the eigen documentation say MKL is supported?

**Comment by junghans** [comment]
Got it, `src/FFT/ei_imklfft_impl.h` is missing.

**Comment by JensWehner** [comment]
jop
