### ISSUE TITLE
Trim values in property class

### ISSUE THREAD

**Issue by JensWehner** [votca/tools#213]
Should we trim values, i.e should 

`<tag>A </tag>` and 
`<tag>A`
`</tag>`

be equivalent to `<tag>A</tag>`  
We do that to string values already but it could violate the XML specs.

**Comment by junghans** [comment]
We do that in `csg_inverse`, too (https://github.com/votca/csg/blob/master/share/scripts/inverse/functions_common.sh#L249), so fine with me as long as we only trim space/tab as the beginning and end.

Kind of what `trim_all()` does: https://github.com/votca/csg/blob/master/share/scripts/inverse/functions_common.sh#L362-L365

**Comment by JensWehner** [comment]
spce tab and linebreak from the end and beginning of the value?

**Comment by junghans** [comment]
Yes

**Comment by JensWehner** [comment]
should be fixed by #365
