### ISSUE TITLE
Check that the calculator input option has a valid input

### ISSUE THREAD

**Issue by felipeZ** [votca/tools#232]
## Motivation
* Unify all the defaults inside the `xml` files.
* Reduce the amount of check performs by each `Calculator.Initialize` method.

## Proposed changes
* Read a new `choices` attribute for each option in the  XML `Calculators` file.
* Check that the value of each option after merging with the *user input* has valid input.
* Introduced 5 new choices for continuous values: `[bool,float, float+, int, int+]` to represent reals, positive reals, integers, and positive integers, respectively.
 
## Example
suppose there is a calculator with the following defaults:
```xml
<options>
  <calculator>
       <opt1 help="first option" default="foo" choices="foo,bar">foo</opt1>
       <opt2 help="second option" default="3.1415" choices="float+">3.1415</opt2> 
 </calculator>
</options>
```
The user can change both `opt1` and `opt2` but the changes must be valid values as declared by `choices`

### Note
The options without a `choices` attribute is skip.

**Comment by JensWehner** [comment]
really nice issue.
