### ISSUE TITLE
Cmake MKL_ThreadingLibrary

### ISSUE THREAD

**Issue by baumeier** [votca/tools#250]
Recent building attempt on our cluster failed upon linking because

`MKL_ThreadingLibrary_LINK_LIBRARY:FILEPATH`

is not found. Cmake does not throw an error. Workaround only possible by adding the correct filename of `libiomp5.so` manually.

**Comment by junghans** [comment]
The lib is searched for here: https://github.com/votca/tools/blob/bfdffabb46eca082e9ebd283ffb5626f247631f2/CMakeModules/FindMKL.cmake#L222
and here
https://github.com/votca/tools/blob/bfdffabb46eca082e9ebd283ffb5626f247631f2/CMakeModules/FindMKL.cmake#L144

**Comment by JensWehner** [comment]
is there a way to search for openmp first and then set it for the mkl instead of the other way round. Because in xtp we are searching for openmp anyway?

**Comment by JensWehner** [comment]
I think this is finished for the moment
