### ISSUE TITLE
generate rst page from help

### ISSUE THREAD

**Issue by junghans** [votca/tools#312]
The `--man` option outputs a manpage, could we add something similar to print out an rst page to include in the website?

**Comment by felipeZ** [comment]
I am working in a script to extract the metadata

**Comment by felipeZ** [comment]
see: [xtp/man branch](https://github.com/votca/xtp/tree/man)
@junghans  are there any `csg` binary that output a manual with the `--man` command? I have only tried the `xtp` command tools

**Comment by junghans** [comment]
Not yet, we only use `—man` in tools, but I would like to switch csg to it as well.

While you are at it could you add an option to output it to a file?

**Comment by junghans** [comment]
Well and could we build it into the application class instead of converting it with a python script?

**Comment by felipeZ** [comment]
@junghans  sure, I am going to work on it :+1:

**Comment by junghans** [comment]
@JensWehner or what do you think?

**Comment by JensWehner** [comment]
So we would have to implement an rst writer for the property class?
