### ISSUE TITLE
Create Rotation Matrix

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/tools#32]
Common requirement is to rotate the positional coordinates of a vec defined in vec.h. It would be convenient to create a rotation matrix based on matrix.h that does just this.

**Comment by JoshuaSBrown** [comment]
For instance when calling the constructor you could pass in phi and theta defining the angles about which the point should be rotated etc.

**Comment by JensWehner** [comment]
if we move at the end of the year from vec and matrix class to eigen it should be pretty easy to just give that.

**Comment by JoshuaSBrown** [comment]
You mean there would not be a need to define a class for this?

**Comment by JensWehner** [comment]
Eigen offers quite some functionality using quaternions and then transforming into rotation matrices and back. So yes, unless it is urgent. In the long term I want to replace the vec and matrix class by Eigen::Vector3d and Eigen::Matrix3d
