### ISSUE TITLE
New table class doesn't read fortan style tables

### ISSUE THREAD

**Issue by junghans** [votca/tools#64]
```
$ cat x
  5.000000000000000E-002  0.000000000000000E+000
  0.150000000000000       0.000000000000000E+000
  0.250000000000000       0.000000000000000E+000
$ csg_resample --in x --out y --grid 0.05:0.1:0.25 --type linear
an error occurred:
invaid type: file x, line 1
```

as a workaround one can do:
```
awk '{print $1+0,$2+0}' x  > x.fixed
```
and
```
 csg_resample --in x.fixed --out y --grid 0.05:0.1:0.25 --type linear
```
will work

**Comment by junghans** [comment]
Yes it the first 3 line of `A-A.dist.tgt` from his user' system: https://groups.google.com/d/msg/votca/FQslEpuGefo/PRr5GOzSDQAJ

Interestingly enough it works in version 1.4.1, so it is regression introduced by the new table class.

**Comment by JensWehner** [comment]
can we not just put a std::replace("E","e") or so in the parser?

**Comment by JoshuaSBrown** [comment]
Sure, that seems like a pretty straightforward solution.

**Comment by JoshuaSBrown** [comment]
I can probably fix this today unless you are volunteering @JensWehner ?

**Comment by JensWehner** [comment]
go ahead.

**Comment by JensWehner** [comment]
no
